services:
  konvertHR-marketing:
    image: konverthr-marketing-frontend
    container_name: konvertHR-marketing-container
    env_file:
      - .env.development.local
    build: .
    ports:
      - "3000:3000"
    restart: always
    # scale: 3
